# NumPy 和陣列導向的程式設計

`NumPy` 可以說是 Python 中最最標準的科學計算、數據分析套件。也因為 `NumPy` 的出現, 讓 Python 有了非常好的數據分析基礎, 一直到現在成為數據分析覇主。

In [1]:
import numpy as np

### 【暖身】 計算平均

某位同學期中考各科成績如下, 請幫他計算成績。

    grades = [77, 85, 56, 90, 66]
    
請計算平均。

In [14]:
s=0
grades = [77, 85, 56, 90, 66]
for i in grades:
    s=s+i # s+=i
print("average={0:6.2f},sum={1}".format (s/len(grades),s))

average= 74.80,sum=374


In [11]:
#note 
#grades = [77, 85, 56, 90, 66] >>建立一個list  grades，其中包含 5 個整數，分別代表 5 科的成績#
#s = 0  >>s，它用來存放所有科目成績的總和
#for i in grades:
# s=s+i # s+=i  >>這是一個 for 迴圈，它會走訪 list中所有element   將i 的值加到 s 上，並更新 s 的值
# print這個字串"但這裡需要做一些format處理,所以使用placeholder{}告訴程式接下來想怎麼format
#.format前告訴我打算怎麼format, format後告訴我想format誰
# 0告訴我們這裡在講第一個element: (s/len(grades), 用:分隔"位置"和"格式化輸出的規則"
#.前面告訴我輸出要有幾個位元(包含數字和小數點)如果不滿6位元會補空白,.後面表示保留小數點後?位, f → 代表浮點數(有小數點), 
# sum {1} 宣告這裡呈現的是位置1, 由於沒有宣告要輸出整數int或小數float,所以這裡答案只要是整數就會輸出整數,小數就會輸出小數


## 1. 陣列導向 101

科學計算一個很核心的概念叫 "array oriented" 的寫法。Array 是 `numpy` 標準的資料結構, 和 list 很像, 但就差了那麼一點點。而這一點點讓我們在計算上是無比的方便。

### 【示範】陣列導向

In [ ]:
#剛剛球平均很麻煩現在改用array可以較快速的運算

In [15]:
grades = [77, 85, 56, 90, 66]
arr=np.array(grades)
arr.mean()

74.8

In [16]:
# np.array(grades)宣告他是numpy中的array接著就能簡單運算
# 但我可能不知道可以做哪些運算可以打完arr後按Tab 就會自動跑出有哪些function可以用

最大值

In [17]:
arr.max()

90

標準差

In [19]:
arr.std()

12.416118556135006

### 【暖身】 換算匯率

假設今天我想查查號稱 Pentax 三公主的 31mm, 43mm, 77mm 三隻 limited 鏡頭在美國賣多少。於是我去 B&H 查了他們的價格分別是:

    prices = [1096.95, 596.95, 896.95]
    
我又查了 Google 匯率 1 美金為 31.71 元。請把三支鏡頭的價格換算為台幣。

In [25]:
prices = [1096.95, 596.95, 896.95]
usdtotwd=31.71
twd_price=[]
for i in prices:
    twd_price.append(i * usdtotwd) 
print (twd_price)

[34784.2845, 18929.2845, 28442.2845]


In [27]:
#如果沒有用append他會逐步算完3個換算價格後, 後念的結果就會覆蓋前面的結果答案紙會呈現28442.2845
# i * usdtotwd 會計算轉換後的價格，然後 .append() 會直接把結果加到 twd_price，不需要 = 來更新變數

先不管這實在有夠醜的數字, 我們要記得在科學計算中:

### 儘可能不要使用迴圈

這可能嗎?

### 【示範】陣列換算匯率

In [26]:
prices = [1096.95, 596.95, 896.95]
prices=np.array(prices)
usdtotwd=31.71
prices*usdtotwd

array([34784.2845, 18929.2845, 28442.2845])

哦哦, 傑克, 這太神奇了!

## 2. 其實 array 還有很多功能

### 【練習】 成績計算

一位老師成績這樣算的:

* 平時成績 20%
* 期中考   35%
* 期未考   45%

有位同學

* 平時成績 85 分
* 期中 70 分
* 期末 80 分

這位同學的學期成績是多少?

In [31]:
grades = np.array([85,70,80])
weights = np.array([0.2, 0.35, 0.45])
grades*weights

array([17. , 24.5, 36. ])

這還不是我們要的最終成績啊!

In [32]:
#兩個都是array格式因此直接相乘也會是array
weight_grades=grades*weights
weight_grades.sum()

77.5

### 【提示】 array 還有很多函數可以用

可以先打入

    weighted_grades.
    
先不要按 `enter` 或 `shift-enter`, 而是按 `tab`...


### 【技巧】 一行完成成績計算

In [33]:
np.dot (grades,weights)

77.5

In [ ]:
#np.dot 這兩個陣列相乘 且要加總起來

## 3. 重要的 array 大變身!

我們在數據分析, 常常要改 array 的型式。

### 【練習】 一個 50 個數字的 array

先想辦法、用亂數做出 50 個數字的 array, 叫做 A 好了。

In [52]:
A=np.random.rand(50)
#rand 表示產生0-1之間的數字
#(50)共50個 是一維陣列, 只會有一個list (只有一個[])
A

array([0.19775432, 0.68411812, 0.83550908, 0.91227273, 0.75564694,
       0.13304779, 0.10876961, 0.62157054, 0.645791  , 0.55584516,
       0.62249048, 0.68545912, 0.85241871, 0.43451264, 0.31804103,
       0.7361014 , 0.22502542, 0.99304966, 0.15089493, 0.54873347,
       0.033975  , 0.61408892, 0.52868323, 0.75624342, 0.06633492,
       0.93270559, 0.61283358, 0.62577989, 0.41462975, 0.34206432,
       0.0076254 , 0.51213379, 0.29910122, 0.29912272, 0.67086842,
       0.06215405, 0.04607246, 0.72977105, 0.39528051, 0.91419817,
       0.05261375, 0.58629272, 0.16439396, 0.8159574 , 0.54525334,
       0.9397931 , 0.44383705, 0.44867443, 0.72680148, 0.05499701])

### 【技巧】 檢查 A 的 `shape`

In [45]:
A.shape

(50,)

In [ ]:
#當我們剛經手或創造一個資料時  一定要先觀察一下shape確保他和我們想像的長相依樣
#(1,) → 代表一維陣列，只有 1 個元素
# (1,1) → 代表二維陣列，形狀是 1 (row)×1(colum)
# (50,)只有 50 個元素，存放在 1D 陣列中
# (50,1) 2D陣列 ROW=50 COLUM=1

### 【技巧】 更改 A 的 shape

In [62]:
A.shape =(5,10)
A
A[0]
A[0,0]
A
# ROW=5 COLUM=10  []是一個ROW的數字
#A[0] 表示1D, 我取這一個ROW裡位置0的數字
# A[5,0]表示2D, 我取這一個ROW=5 COLUM=0的數字
# A[7,5,0]表示3D, 我取第7個矩陣 ROW=5 COLUM=0的數字

array([[0.19775432, 0.68411812, 0.83550908, 0.91227273, 0.75564694,
        0.13304779, 0.10876961, 0.62157054, 0.645791  , 0.55584516],
       [0.62249048, 0.68545912, 0.85241871, 0.43451264, 0.31804103,
        0.7361014 , 0.22502542, 0.99304966, 0.15089493, 0.54873347],
       [0.033975  , 0.61408892, 0.52868323, 0.75624342, 0.06633492,
        0.93270559, 0.61283358, 0.62577989, 0.41462975, 0.34206432],
       [0.0076254 , 0.51213379, 0.29910122, 0.29912272, 0.67086842,
        0.06215405, 0.04607246, 0.72977105, 0.39528051, 0.91419817],
       [0.05261375, 0.58629272, 0.16439396, 0.8159574 , 0.54525334,
        0.9397931 , 0.44383705, 0.44867443, 0.72680148, 0.05499701]])

### 【技巧】 也可以用 `reshape`

但要注意, reshape 並沒有改原來的陣列。

In [64]:
A.reshape (10,5)

array([[0.19775432, 0.68411812, 0.83550908, 0.91227273, 0.75564694],
       [0.13304779, 0.10876961, 0.62157054, 0.645791  , 0.55584516],
       [0.62249048, 0.68545912, 0.85241871, 0.43451264, 0.31804103],
       [0.7361014 , 0.22502542, 0.99304966, 0.15089493, 0.54873347],
       [0.033975  , 0.61408892, 0.52868323, 0.75624342, 0.06633492],
       [0.93270559, 0.61283358, 0.62577989, 0.41462975, 0.34206432],
       [0.0076254 , 0.51213379, 0.29910122, 0.29912272, 0.67086842],
       [0.06215405, 0.04607246, 0.72977105, 0.39528051, 0.91419817],
       [0.05261375, 0.58629272, 0.16439396, 0.8159574 , 0.54525334],
       [0.9397931 , 0.44383705, 0.44867443, 0.72680148, 0.05499701]])

In [ ]:
# reshape 並沒有改原來的陣列。 reshape完視覺上如上
#但如果你print A(如下 他還是會變成原本A.shape =(5,10)的樣子

In [65]:
A

array([[0.19775432, 0.68411812, 0.83550908, 0.91227273, 0.75564694,
        0.13304779, 0.10876961, 0.62157054, 0.645791  , 0.55584516],
       [0.62249048, 0.68545912, 0.85241871, 0.43451264, 0.31804103,
        0.7361014 , 0.22502542, 0.99304966, 0.15089493, 0.54873347],
       [0.033975  , 0.61408892, 0.52868323, 0.75624342, 0.06633492,
        0.93270559, 0.61283358, 0.62577989, 0.41462975, 0.34206432],
       [0.0076254 , 0.51213379, 0.29910122, 0.29912272, 0.67086842,
        0.06215405, 0.04607246, 0.72977105, 0.39528051, 0.91419817],
       [0.05261375, 0.58629272, 0.16439396, 0.8159574 , 0.54525334,
        0.9397931 , 0.44383705, 0.44867443, 0.72680148, 0.05499701]])

### 【技巧】 拉平 `ravel`

雖然你想一想就知道可以用 `shape` 或 `reshape` 把多維陣列拉成一維。不過用 `ravel` 很潮。

In [68]:
# 改回1D
A.ravel()


array([0.19775432, 0.68411812, 0.83550908, 0.91227273, 0.75564694,
       0.13304779, 0.10876961, 0.62157054, 0.645791  , 0.55584516,
       0.62249048, 0.68545912, 0.85241871, 0.43451264, 0.31804103,
       0.7361014 , 0.22502542, 0.99304966, 0.15089493, 0.54873347,
       0.033975  , 0.61408892, 0.52868323, 0.75624342, 0.06633492,
       0.93270559, 0.61283358, 0.62577989, 0.41462975, 0.34206432,
       0.0076254 , 0.51213379, 0.29910122, 0.29912272, 0.67086842,
       0.06215405, 0.04607246, 0.72977105, 0.39528051, 0.91419817,
       0.05261375, 0.58629272, 0.16439396, 0.8159574 , 0.54525334,
       0.9397931 , 0.44383705, 0.44867443, 0.72680148, 0.05499701])

## 4. 快速 array 生成法

### 【技巧】 都是 0 的 array

In [ ]:
#以下生成法做影像處理常會用到可以描述影響中特定位置 

In [70]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [72]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

### 【技巧】 都是 1 的 array

In [71]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

### 【技巧】單位矩陣

In [73]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 【技巧】給定範圍均勻生出 n 個點

In [77]:
x=np.linspace(0,10,100)
x

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

In [ ]:
#0-10均勻生出100個點

### 【技巧】`range` 的 array 版

就是 `arange`。

In [78]:
np.arange (1,10,0.2)

array([1. , 1.2, 1.4, 1.6, 1.8, 2. , 2.2, 2.4, 2.6, 2.8, 3. , 3.2, 3.4,
       3.6, 3.8, 4. , 4.2, 4.4, 4.6, 4.8, 5. , 5.2, 5.4, 5.6, 5.8, 6. ,
       6.2, 6.4, 6.6, 6.8, 7. , 7.2, 7.4, 7.6, 7.8, 8. , 8.2, 8.4, 8.6,
       8.8, 9. , 9.2, 9.4, 9.6, 9.8])

In [ ]:
#1-10每次增加0.2

## 5. 超重要 `axis` 觀念

初學 `numpy` 很多人有點弄不清楚 `axis` 概念。其實掌握矩陣, 或很像矩陣的陣列都是「先列後行」就可以!

我們先弄個 array 來練習。

In [80]:
A=np.arange(10).reshape(2,5)
A
#從0開始到10 (10不算) 每次變動方向是1


array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 【重點】 一列一列算下來是 `axis=0`

![axis=0](images/axis0.png)

In [81]:
A.sum(axis=0)
#axis=0指的是同一colum

array([ 5,  7,  9, 11, 13])

### 【重點】 一行一行算過去是 `axis=1`

![axis=1](images/axis1.png)

In [82]:
A.sum(axis=1)
#axis=1指的是同一row

array([10, 35])

### 【提示】當然也有可能全部算

In [83]:
A.sum()
#都不設定就是全都sum

45

## 6. array 過濾器

篩出我們要的資料, 這樣的技巧非常重要!

### 【例子】篩出大於 0 的數

我們有個陣列, 想找出大於 0 的數。<br>
L = np.array([3, -2, -1, 5, 7, -3])

In [87]:
L = np.array([3, -2, -1, 5, 7, -3])
L

array([ 3, -2, -1,  5,  7, -3])

我們可以很白痴的自己判斷...<br>
c = np.array([True,False,False,True,True,False])

In [88]:
c = np.array([True,False,False,True,True,False])

In [89]:
L[c]

array([3, 5, 7])

這是做啥呢? 我們可以瞬間...

除了自己做很白痴, 這看來很厲害!

事實上我們可以叫 `numpy` 做!numpy可以幫我們挑>0

In [90]:
L>0

array([ True, False, False,  True,  True, False])

這有點強, 我們還可以一次到位!

In [94]:
L=L[L>0]
L

array([3, 5, 7])

## 7. 次元切割刀

`numpy` 中 array 的切割法和 list 很像。

In [96]:
x=np.arange(10)#亂數生成0-9 
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [97]:
x[3:7]
#切割  從第三個位置切到7-1個位置

array([3, 4, 5, 6])

### 【技巧】2維陣列切法

記得先列後行!

In [101]:
x=np.arange(10)#亂數生成0-9 
x.shape=(2,5)
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

要所有的row, 切出行 1-3 位置。

In [102]:
x[:,1:3]
#,前是row沒有特定設定頭尾表示所有row都要
#,後是colum ,切出colum 1-3 (不包含3)

array([[1, 2],
       [6, 7]])

要所有的行col, 切出第 1 列row!

In [103]:
x[1,:]
#,前是row 若止寫一個字表是特定位置

array([5, 6, 7, 8, 9])

## 8. `NumPy` 的 `zip` 和 `unzip`

之前我們介紹 list 可以用 `zip` 和 `unzip` (其實還是 `zip`) 做到的資料格式變換, 在 array 中怎麼做呢?

![zip and unzip](images/zip.png)

### 【重點】array 的 `zip`

![array zip](images/arrzip.png)

In [105]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

In [106]:
X=np.c_[x,y]
X
# C_ 指的是用COLUM的方式把資料放進來
#第一個COLUM是x 第二個COLUM是y

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [107]:
Y=np.r_[x,y]
Y
# R_ 指的是用row的方式把資料放進來
#但這邊和上方不同,不會x當row1 y當row2 (這樣就根源資料沒有兩樣), 而是會接續成為同一個row

array([1, 2, 3, 4, 5, 6, 7, 8])

### 【重點】array 的 `unzip`

這裡其實只需要用到 array 的切割法...

![array zip](images/arrunzip.png)

In [109]:
X[:,0]

array([1, 2, 3, 4])

In [110]:
X[1,:]

array([2, 6])